# 运行模式(debug:调试,test:测试,release:正式)
RunMode = "debug"

# 是否启用swagger
Swagger = true

# 启动时是否打印配置参数
PrintConfig = true

[HTTP]
# http监听地址
Host = "0.0.0.0"
# http监听端口
Port = 10088
# 证书路径
CertFile = ""
# 证书密钥
KeyFile = ""
# http优雅关闭等待超时时长(单位秒)
ShutdownTimeout = 30
# 允许的最大内容长度(64M)
MaxContentLength = 67108864

[CORS]
# 是否启用
Enable = true
# 允许跨域请求的域名列表(*表示全部允许)
AllowOrigins = ["*"]
# 允许跨域请求的请求方式列表
AllowMethods = ["GET","POST","PUT","DELETE","PATCH","OPTIONS"]
# 允许客户端与跨域请求一起使用的非简单标头的列表
AllowHeaders = ["Content-Length, Access-Control-Allow-Origin,Access-Control-Allow-Headers, Content-Type"]
# 请求是否可以包含cookie，HTTP身份验证或客户端SSL证书等用户凭据
AllowCredentials = true
# 可以缓存预检请求结果的时间（以秒为单位）
MaxAge = 7200

[GZIP]
# 是否启用
Enable = false
# 排除的文件扩展名
ExcludedExtentions = [".png",".gif",".jpeg",".jpg"]
# 排除的请求路径
ExcludedPaths = []

[Gorm]
# 是否开启调试模式
Debug = true
# 数据库类型(目前支持的数据库类型：sqlite3/postgres)
DBType = "postgres"
# 设置连接可以重用的最长时间(单位：秒)
MaxLifetime = 7200
# 设置数据库的最大打开连接数
MaxOpenConns = 150
# 设置空闲连接池中的最大连接数
MaxIdleConns = 50
# 是否启用自动映射数据库表结构
EnableAutoMigrate = true

[Postgres]
# 连接地址
# Host = "postgres"
Host = "127.0.0.1"
# 连接端口
Port= 8001
# 用户名
User = "admin"
# 密码
Password = "admin"
# 数据库
DBName = "todo"
# SSL模式
SSLMode = "disable"

[Sqlite3]
# 数据库路径
Path = "data/gin-admin.db"
